# Generated by Django 4.2.6 on 2023-10-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='annotation',
        ),
        migrations.AddField(
            model_name='documents',
            name='annotations',
            field=models.ManyToManyField(blank=True, to='documents.annotation'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.CharField(max_length=4055),
        ),
    ]
