# Generated by Django 4.2.6 on 2023-10-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_documents_annotation_documents_annotations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='annotations',
            new_name='annotation',
        ),
    ]
